# NUMPY 

## Krish Naik - Tutorial 4 - Numpy and Inbuilt Functions Tutorial

## Numpy Array

In [1]:
# install Numpy via Anaconda
conda install numpy

SyntaxError: invalid syntax (<ipython-input-1-6a730d413184>, line 2)

In [ ]:
# another way to install numpy
pip install numpy

In [3]:
# import Numpy
import numpy as np

In [4]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [66]:
my_lst1=[1,2,3,4,5]
my_lst2=[6,7,8,7,9]
my_lst3=[9,7,7,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [67]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 7, 9],
       [9, 7, 7, 8, 9]])

In [68]:
arr.shape

(3, 5)

In [69]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 7],
       [9, 9, 7],
       [7, 8, 9]])

In [30]:
arr.shape

(3, 5)

## Indexing

In [70]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 7, 9],
       [9, 7, 7, 8, 9]])

In [71]:
arr1=np.array([1,2,3,4,5,6,7,8,9])

In [72]:
arr1[3]

4

In [117]:
arr1[2,4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [118]:
arr[1,3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [119]:
arr[:,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [37]:
arr[0:2,2:3]

array([[3],
       [8]])

In [39]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 7, 9]])

In [40]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [41]:
arr[1:3,3:5]

array([[7, 9],
       [8, 9]])

In [42]:
arr[1:,3:]

array([[7, 9],
       [8, 9]])

In [46]:
#assignment
arr[1:,2:4]

array([[8, 7],
       [7, 8]])

In [47]:
#single dimension
arr[1,1:4]

array([7, 8, 7])

In [50]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 7, 9],
       [9, 7, 7, 8, 9]])

In [52]:
arr=np.arange(0,10)

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr=np.arange(0,10,step=2)

In [57]:
arr

array([0, 2, 4, 6, 8])

In [76]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [77]:
#copy() function & broadcasting
arr

array([0, 2, 4, 6, 8])

In [79]:
arr[3:]=100

In [80]:
arr

array([  0,   2,   4, 100, 100])

In [88]:
arr1=arr

In [89]:
arr1[3:]=500

In [90]:
arr1

array([  0,   2,   4, 500, 500])

In [91]:
arr1

array([  0,   2,   4, 500, 500])

In [92]:
 arr1=arr.copy()

In [94]:
print(arr)
arr1[3:]=1000
print (arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [95]:
#Useful conditions in Exploratory Data Analysis (EDR)
val=2
arr<2


array([ True, False, False, False, False])

In [96]:
arr*2

array([   0,    4,    8, 1000, 1000])

In [97]:
arr/2

array([  0.,   1.,   2., 250., 250.])

In [98]:
arr%2

array([0, 0, 0, 0, 0], dtype=int32)

In [101]:
arr[arr<300]

array([0, 2, 4])

In [103]:
np.ones(4)

array([1., 1., 1., 1.])

In [104]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [106]:
np.ones(4, dtype=str)

array(['1', '1', '1', '1'], dtype='<U1')

In [107]:
np.ones(4, dtype=float)

array([1., 1., 1., 1.])

In [109]:
#random distribution
np.random.rand(3,3)

array([[0.84296305, 0.74858187, 0.63252826],
       [0.00312067, 0.85744578, 0.11656729],
       [0.11372168, 0.75933807, 0.45196856]])

In [111]:
arr_ex=np.random.randn(4,4)

In [112]:
arr_ex

array([[ 1.55103503,  0.159892  , -1.08695027,  0.73289671],
       [-1.43104136, -0.46655713, -0.78324741,  0.30817466],
       [ 2.61811873,  0.01818687,  0.52619808, -0.80195928],
       [-0.99056265, -1.46290152,  1.21388473, -0.64570964]])

In [113]:
#please watch statistcs videos and learn 'Standard Normal Distribution'

In [115]:
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.


In [116]:
import pandas as pd